namespace DemoRestAPI.Users.Response
{
    public enum UserEnum
    {
        REGISTER_SUCCESS,
        REGISTER_FAILED,
        LOGIN_SUCCESS,
        LOGIN_FAILED,
        REFRESHTOKEN_GENERATION_FAILED,
        PRINCIPAL_NOT_FOUND,
        PRINCIPAL_NAME_NOT_FOUND,
        USER_NOT_FOUND,
        USER_NOT_UPDATED,
        REFRESHTOKEN_NOT_EXPIRED,
        REFRESHTOKEN_NOT_SAME,
        ACCESSTOKEN_GENERATION_FAILED,
        DEVICE_NOT_FOUND,
        WAREHOUSE_NOT_FOUND
    }
}
